name: Build TauArgusJava.dll

on:
  push:
    branches: [ "Keep_status" ]

jobs:
  setupMinGW:
    runs-on: windows-latest
    
    steps:
    - uses: egor-tensin/setup-mingw@v2
    - name: SetUp MinGW
    - with:
        platform: x86
  
  setupJava:
    needs: setupMinGW
    runs-on: windows-latest
    
    steps:
    - uses: actions/setup-java@v3
    - name: SetUp Java Zulu 8
    - with:
        distribution: 'zulu'
        java-version: '8'
        platform: x86

  build:
    needs: [setupMinGW, setupJava]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make dll
    - run: make
